### ISSUE TITLE
Crash in text box layout when text box is too narrow

### ISSUE THREAD

**Issue by andrewhickman** [linebender/druid#1297]
I ran into this on Windows 10, using version e01c99502c8c500e2f7f663e01789ffd4b68ca13

Repro steps:
- In the "text" example, increase the padding a bit on line 115: `.padding((SPACER_SIZE * 8.0, SPACER_SIZE))`
- Run the example
- Set line break mode to "wrap"
- Decrease the width of the window

On my system this crashes with the following backtrace:

<details><summary>Backtrace</summary>

```

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BackendError(hresult 80070057)', C:\Users\andre\Repositories\druid\druid\src\text\layout.rs:301:72
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\option.rs:1221
   3: core::result::Result<piet_direct2d::text::D2DTextLayout, piet::error::Error>::unwrap<piet_direct2d::text::D2DTextLayout,piet::error::Error>
             at C:\Users\andre\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:973
   4: druid::text::layout::TextLayout<text::AppState>::rebuild_if_needed<text::AppState>
             at .\src\text\layout.rs:301
   5: druid::widget::label::{{impl}}::layout<text::AppState>
             at .\src\widget\label.rs:534
   6: druid::widget::controller::{{impl}}::layout<text::AppState,druid::widget::label::RawLabel<text::AppState>,text::LabelController>
             at .\src\widget\controller.rs:125
   7: druid::widget::widget::{{impl}}::layout<text::AppState>
             at .\src\widget\widget.rs:251
   8: druid::core::WidgetPod<text::AppState, alloc::boxed::Box<Widget<text::AppState>>>::layout<text::AppState,alloc::boxed::Box<Widget<text::AppState>>>
             at .\src\core.rs:491
   9: druid::widget::container::{{impl}}::layout<text::AppState>
             at .\src\widget\container.rs:157
  10: druid::widget::widget::{{impl}}::layout<text::AppState>
             at .\src\widget\widget.rs:251
  11: druid::widget::sized_box::{{impl}}::layout<text::AppState>
             at .\src\widget\sized_box.rs:153
  12: druid::widget::widget::{{impl}}::layout<text::AppState>
             at .\src\widget\widget.rs:251
  13: druid::core::WidgetPod<text::AppState, alloc::boxed::Box<Widget<text::AppState>>>::layout<text::AppState,alloc::boxed::Box<Widget<text::AppState>>>
             at .\src\core.rs:491
  14: druid::widget::padding::{{impl}}::layout<text::AppState>
             at .\src\widget\padding.rs:92
  15: druid::widget::widget::{{impl}}::layout<text::AppState>
             at .\src\widget\widget.rs:251
  16: druid::core::WidgetPod<text::AppState, alloc::boxed::Box<Widget<text::AppState>>>::layout<text::AppState,alloc::boxed::Box<Widget<text::AppState>>>
             at .\src\core.rs:491
  17: druid::widget::container::{{impl}}::layout<text::AppState>
             at .\src\widget\container.rs:157
  18: druid::core::WidgetPod<text::AppState, druid::widget::container::Container<text::AppState>>::layout<text::AppState,druid::widget::container::Container<text::AppState>>
             at .\src\core.rs:491
  19: druid::widget::scroll::{{impl}}::layout<text::AppState,druid::widget::container::Container<text::AppState>>
             at .\src\widget\scroll.rs:142
  20: druid::widget::widget::{{impl}}::layout<text::AppState>
             at .\src\widget\widget.rs:251
  21: druid::core::WidgetPod<text::AppState, alloc::boxed::Box<Widget<text::AppState>>>::layout<text::AppState,alloc::boxed::Box<Widget<text::AppState>>>
             at .\src\core.rs:491
  22: druid::widget::flex::{{impl}}::layout<text::AppState>
             at .\src\widget\flex.rs:653
  23: druid::widget::widget::{{impl}}::layout<text::AppState>
             at .\src\widget\widget.rs:251
  24: druid::core::WidgetPod<text::AppState, alloc::boxed::Box<Widget<text::AppState>>>::layout<text::AppState,alloc::boxed::Box<Widget<text::AppState>>>
             at .\src\core.rs:491
  25: druid::window::Window<text::AppState>::layout<text::AppState>
             at .\src\window.rs:367
  26: druid::window::Window<text::AppState>::prepare_paint<text::AppState>
             at .\src\window.rs:325
  27: druid::win_handler::Inner<text::AppState>::prepare_paint<text::AppState>
             at .\src\win_handler.rs:305
  28: druid::win_handler::AppState<text::AppState>::prepare_paint_window<text::AppState>
             at .\src\win_handler.rs:501
  29: druid::win_handler::{{impl}}::prepare_paint<text::AppState>
             at .\src\win_handler.rs:738
  30: druid_shell::platform::windows::window::{{impl}}::window_proc
             at C:\Users\andre\Repositories\druid\druid-shell\src\platform\windows\window.rs:646
  31: druid_shell::platform::windows::window::win_proc_dispatch
             at C:\Users\andre\Repositories\druid\druid-shell\src\platform\windows\window.rs:1445
  32: CallWindowProcW
  33: DispatchMessageW
  34: IsWindowVisible
  35: KiUserCallbackDispatcher
  36: NtUserMessageCall
  37: GetWindowTextW
  38: MapWindowPoints
  39: IsCompositionActive
  40: Ordinal96
  41: IsCompositionActive
  42: IsCompositionActive
  43: GetWindowTextW
  44: druid_shell::platform::windows::window::win_proc_dispatch
             at C:\Users\andre\Repositories\druid\druid-shell\src\platform\windows\window.rs:1457
  45: CallWindowProcW
  46: DispatchMessageW
  47: IsWindowVisible
  48: KiUserCallbackDispatcher
  49: NtUserMessageCall
  50: GetWindowTextW
  51: MapWindowPoints
  52: IsCompositionActive
  53: Ordinal96
  54: IsCompositionActive
  55: IsCompositionActive
  56: GetWindowTextW
  57: druid_shell::platform::windows::window::win_proc_dispatch
             at C:\Users\andre\Repositories\druid\druid-shell\src\platform\windows\window.rs:1457
  58: CallWindowProcW
  59: DispatchMessageW
  60: druid_shell::platform::windows::application::Application::run
             at C:\Users\andre\Repositories\druid\druid-shell\src\platform\windows\application.rs:135
  61: druid_shell::application::Application::run
             at C:\Users\andre\Repositories\druid\druid-shell\src\application.rs:153
  62: druid::app::AppLauncher<text::AppState>::launch<text::AppState>
             at .\src\app.rs:181
  63: text::main
             at .\examples\text.rs:102
  64: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at C:\Users\andre\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `C:\Users\andre\Repositories\druid\target\debug\examples\text.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

</details>

**Comment by cmyr** [comment]
I suspect this is the result of label passing a negative width to layout. If you'd like to test this out, you can modify `label.rs:533` and add `.max(0.0)` to `width`.

In any case, piet should be defensive about this, and not allow negative width.

**Comment by andrewhickman** [comment]
Yep, that fixed it 👍

**Comment by cmyr** [comment]
great, I'll want to fix this in piet but we can also be defensive here for now. If you wanted to open a PR, the fix I would add here would be in `src/text/layout.rs`, in the `set_wrap_width` method; I would just make sure that is >= 0.0.

Just as a note: you can set a minimum size for a window, and I think this should be set for most actual applications? I actually think this should have reasonable defaults, and if you want to be able to resize windows to be very small you should have to specify that manually, but that's also a separate issue. 😁
