### ISSUE TITLE
Using `Label` as a top-level Widget panics

### ISSUE THREAD

**Issue by andrewhickman** [linebender/druid#1345]
For example
```
use druid::widget::Label;
use druid::{AppLauncher, WindowDesc};

pub fn main() {
    let main_window = WindowDesc::new(|| Label::new("hello"));

    AppLauncher::with_window(main_window)
        .launch(())
        .expect("Failed to launch application");
}
```
panics with
```
thread 'main' panicked at 'TextLayout::draw called without rebuilding layout object. Text was 'hello'', druid\src\text\layout.rs:352:9
```
It seems that the top-level widget gets `paint` called before `layout`. Wrapping the label in something like `Padding` resolves the panic

I tested this on Windows 10 with druid version 9d166f614ba3e70d54a684e3b8f74b1e5b5ee3a3

**Comment by andrewhickman** [comment]
The full backtrace is 
```
thread 'main' panicked at 'TextLayout::draw called without rebuilding layout object. Text 
was 'hello'', druid\src\text\layout.rs:352:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:429
   2: druid::text::layout::TextLayout<alloc::sync::Arc<str>>::draw<alloc::sync::Arc<str>,kurbo::point::Point>
             at .\druid\src\text\layout.rs:352
   3: druid::widget::label::RawLabel<alloc::sync::Arc<str>>::draw_at<alloc::sync::Arc<str>,kurbo::point::Point>
             at .\druid\src\widget\label.rs:269
   4: druid::widget::label::{{impl}}::paint<alloc::sync::Arc<str>>
             at .\druid\src\widget\label.rs:559
   5: druid::widget::label::{{impl}}::paint<text::AppState>
             at .\druid\src\widget\label.rs:509
   6: druid::widget::widget::{{impl}}::paint<text::AppState>
             at .\druid\src\widget\widget.rs:255
   7: druid::core::WidgetPod<text::AppState, alloc::boxed::Box<Widget<text::AppState>>>::paint_raw<text::AppState,alloc::boxed::Box<Widget<text::AppState>>>
             at .\druid\src\core.rs:391
   8: druid::window::{{impl}}::paint::{{closure}}<text::AppState>
             at .\druid\src\window.rs:401
   9: druid::contexts::PaintCtx::with_child_ctx<druid_shell::region::Region,closure-0>
             at .\druid\src\contexts.rs:648
  10: druid::window::Window<text::AppState>::paint<text::AppState>
             at .\druid\src\window.rs:401
  11: druid::window::Window<text::AppState>::do_paint<text::AppState>
             at .\druid\src\window.rs:354
  12: druid::win_handler::Inner<text::AppState>::paint<text::AppState>
             at .\druid\src\win_handler.rs:317
  13: druid::win_handler::AppState<text::AppState>::paint_window<text::AppState>
             at .\druid\src\win_handler.rs:514
  14: druid::win_handler::{{impl}}::paint<text::AppState>
             at .\druid\src\win_handler.rs:770
  15: druid_shell::platform::windows::window::WndState::render
             at .\druid-shell\src\platform\windows\window.rs:446
  16: druid_shell::platform::windows::window::{{impl}}::window_proc
             at .\druid-shell\src\platform\windows\window.rs:826
  17: druid_shell::platform::windows::window::win_proc_dispatch
             at .\druid-shell\src\platform\windows\window.rs:1455
  18: CallWindowProcW
  19: DispatchMessageW
  20: SendMessageTimeoutW
  21: KiUserCallbackDispatcher
  22: NtUserShowWindow
  23: druid_shell::platform::windows::window::WindowHandle::show
             at .\druid-shell\src\platform\windows\window.rs:1526
  24: druid_shell::window::WindowHandle::show
  25: druid::app::AppLauncher<text::AppState>::launch<text::AppState>
             at .\druid\src\app.rs:177
  26: text::main
             at .\druid\examples\text.rs:102
  27: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at C:\Users\andre\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
```
It looks like the reason adding padding solves the issue, is that before`layout` is called on the label, this condition in `WidgetPod::paint_impl` is true and so the label is never drawn.
```
if !paint_if_not_visible && !ctx.region().intersects(self.state.paint_rect()) {
    return;
}
```
The top level WidgetPod is painted using `paint_raw`, so it skips that condition

**Comment by Finnerale** [comment]
This seems to be a Windows specific problem, at least I can't reproduce it on Linux.

**Comment by cmyr** [comment]
Interesting! I'm also not able to reproduce on macOS. Paint really shouldn't be called before `WindowConnected` is received, so that's definitely something to investigate.

**Comment by oScape** [comment]
hi,

I just fork the repository and pull it on my computer, a Windows 10.
I used it as source dependecy and it work out of the box:
```
druid = { src = "./../druid", branch = "master" }
```

**Comment by andrewhickman** [comment]
So the sequence of events on Windows is (based on my very limited understanding of this code, there might be interesting stuff I'm skipping over):

- The window gets `WM_SIZE` 
  - This calls `WinHandler::size` which invalidates the window handles
  - This calls `WndState::render` which calls `WinHandler::paint`. This is the point at which the crash happens
- The window gets `WM_PAINT`.
  - This calls `WinHandler::prepare_layout` which handles the layout
  - Then we go into `WndState::render -> WinHandler::paint` again

**Comment by cmyr** [comment]
Hmm, so I can think of two possible solutions:

- We could not call `render` in `WM_SIZE`. I tested this, and it seems to work, but there might be some reason we do this.
- We could continue to call `render` in `WM_SIZE`, and just call `prepare_paint` before we do so.

I would prefer the solution that removes code versus adds code, but without knowing more about the rationale for the original solution I am more confident in the second.

**Comment by andrewhickman** [comment]
This no longer panics as of 75ecc4084b41bb012f92aec54e17138d24e2c90e

**Comment by jneem** [comment]
:tada: although to be honest I'm not completely sure why. I even looked at this issue before writing that pr, but it seemed unrelated...
