### ISSUE TITLE
druid-shell crashed on Windows 7

### ISSUE THREAD

**Issue by Steve-xmh** [linebender/druid#1587]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: hresult 80004002', C:\Users\user\.cargo\git\checkouts\druid-f71533f3d81c0bc8\a9e8b01\druid-shell\src\platform\windows\window.rs:1231:48
stack backtrace:
   0:        0x13f8d1265 - <unknown>
   1:        0x13f8ec6cb - <unknown>
   2:        0x13f8cd7ed - <unknown>
   3:        0x13f8d3efd - <unknown>
   4:        0x13f8d39c9 - <unknown>
   5:        0x13f8d47b0 - <unknown>
   6:        0x13f8d42e1 - <unknown>
   7:        0x13f8d1c3f - <unknown>
   8:        0x13f8d4239 - <unknown>
   9:        0x13f8eaf50 - <unknown>
  10:        0x13f8ead73 - <unknown>
  11:        0x13f86ccef - <unknown>
  12:        0x13f830b38 - <unknown>
  13:        0x13f7f9ae1 - <unknown>
  14:        0x13f690345 - <unknown>
  15:        0x13f679126 - <unknown>
  16:        0x13f679e12 - <unknown>
  17:        0x13f58cc5f - <unknown>
  18:        0x13f60f0ab - <unknown>
  19:        0x13f58f8ab - <unknown>
  20:        0x13f66c481 - <unknown>
  21:        0x13f8d4947 - <unknown>
  22:        0x13f66c453 - <unknown>
  23:        0x13f58ce10 - <unknown>
  24:        0x13f8f3604 - <unknown>
  25:         0x7701652d - BaseThreadInitThunk
  26:         0x7714c521 - RtlUserThreadStart
```
Edit:

I tried the `widget-gallery` example, compiled on Windows 10, running on Windows 7, output same error:
```
INFO  [druid_shell::platform::windows::util] No shcore.dll
INFO  [druid_shell::platform::windows::util] Could not load `GetDpiForSystem`. Windows 10 or later is needed
INFO  [druid_shell::platform::windows::util] Could not load `GetDpiForWindow`. Windows 10 or later is needed
INFO  [druid_shell::platform::windows::util] Could not load `SetProcessDpiAwarenessContext`. Windows 10 or later is needed
INFO  [druid_shell::platform::windows::util] Could not load `GetSystemMetricsForDpi`. Windows 10 or later is needed
DEBUG [druid::localization] available locales [], current en-US
DEBUG [druid::localization] resolved: [en-US]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: hresult 80004002', C:\Users\user\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\druid-shell-0.7.0\src\platform\windows\window.rs:1231:48
stack backtrace:
   0:        0x13fafc8b5 - <unknown>
   1:        0x13fb1260b - <unknown>
   2:        0x13faf97bd - <unknown>
   3:        0x13faff54d - <unknown>
   4:        0x13faff019 - <unknown>
   5:        0x13faffe00 - <unknown>
   6:        0x13faff931 - <unknown>
   7:        0x13fafd28f - <unknown>
   8:        0x13faff889 - <unknown>
   9:        0x13fb10e90 - <unknown>
  10:        0x13fb10cb3 - <unknown>
  11:        0x13fa33aff - <unknown>
  12:        0x13f9f7208 - <unknown>
  13:        0x13f9ba501 - <unknown>
  14:        0x13f7f7431 - <unknown>
  15:        0x13f84c446 - <unknown>
  16:        0x13f84cd2f - <unknown>
  17:        0x13f7dbf8b - <unknown>
  18:        0x13f85853b - <unknown>
  19:        0x13f845ffb - <unknown>
  20:        0x13f8647b1 - <unknown>
  21:        0x13fafff97 - <unknown>
  22:        0x13f864783 - <unknown>
  23:        0x13f7dd700 - <unknown>
  24:        0x13fb196b4 - <unknown>
  25:         0x7701652d - BaseThreadInitThunk
  26:         0x7714c521 - RtlUserThreadStart
```

**Comment by Steve-xmh** [comment]
Closed, fixed when updated Windows 7.
