### ISSUE TITLE
#1988 breaks `sub_window` example

### ISSUE THREAD

**Issue by Maan2003** [linebender/druid#1998]
#1988 breaks `sub_window` example. Hover on the text for tooltip second time and you'll get
```
Sep 29 16:51:31.659 ERROR druid::window: No widget found for timer TimerToken(1)
thread 'main' panicked at 'supplied instant is later than self', library\std\src\time.rs:281:48
```
_PS: Im on Windows_

Useful parts of backtrace:
```
   5: std::time::impl$5::sub
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\/library\std\src\time.rs:407
   6: sub_window::impl$1::event<sub_window::HelloState,druid::widget::label::Label<sub_window::HelloState> >
             at .\druid\examples\sub_window.rs:119
```

_Originally posted by @sjoshid in https://github.com/linebender/druid/issues/1988#issuecomment-930535113_

**Comment by sjoshid** [comment]
It's not just the `sub_window` example that is broken. `timers` example is also broken. Even the cursor blinking on textboxes is broken. This means everything related to timers is broken. :(

**Comment by Maan2003** [comment]
I have no idea how the patch can break timers on windows, our interaction with druid shell does not change at all.

**Comment by Maan2003** [comment]
weird, windows backend is reusing TimerTokens which is not done in other backends

**Comment by sjoshid** [comment]
> I have no idea how the patch can break timers on windows, our interaction with druid shell does not change at all.

Confuses me too TBH. 

> weird, windows backend is reusing TimerTokens which is not done in other backends

Removing that resusing piece of code does fix this issue. But unless someone knows the reason _why_ it was added, maybe best not to remove it??
