### ISSUE TITLE
uncaught exception on key press on MacOS

### ISSUE THREAD

**Issue by droundy** [linebender/druid#2197]
You can reproduce this error on my [breaks program with `cargo run`](https://github.com/droundy/breaks).

When the window pops up, if I type an arrow key (or a few others) I get a crash that looks like:
```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/breaks`
2022-06-04T18:30:43.774900Z DEBUG druid::localization: available locales [], current en-US
2022-06-04T18:30:43.775061Z DEBUG druid::localization: resolved: [en-US]
2022-06-04 11:30:45.262 breaks[89208:25067372] +[NSView doCommandBySelector:]: unrecognized selector sent to class 0x20da573e8
thread 'main' panicked at 'Uncaught exception <NSException: 0x600001793810>', /Users/davidroundy/misc-src/druid/druid-shell/src/backend/mac/text_input.rs:270:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The backtrace is very long and doesn't look very helpful, but I'll include it here just in case:
```
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/breaks`
2022-06-04T18:31:03.286086Z DEBUG druid::localization: available locales [], current en-US
2022-06-04T18:31:03.286239Z DEBUG druid::localization: resolved: [en-US]
2022-06-04 11:31:05.042 breaks[89231:25067574] +[NSView doCommandBySelector:]: unrecognized selector sent to class 0x20da573e8
thread 'main' panicked at 'Uncaught exception <NSException: 0x600001c78f30>', /Users/davidroundy/misc-src/druid/druid-shell/src/backend/mac/text_input.rs:270:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_display
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:73:5
   3: druid_shell::backend::mac::text_input::do_command_by_selector
             at /Users/davidroundy/misc-src/druid/druid-shell/src/backend/mac/text_input.rs:270:22
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <(A,) as objc::message::MessageArguments>::invoke
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  41: objc::message::platform::send_unverified::{{closure}}
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27:9
  42: objc_exception::try::{{closure}}
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_exception-0.1.2/src/lib.rs:68:31
  43: objc_exception::try_no_ret::try_objc_execute_closure
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_exception-0.1.2/src/lib.rs:34:9
  44: RustObjCExceptionTryCatch
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_exception-0.1.2/extern/exception.m:10:9
  45: objc_exception::try_no_ret
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_exception-0.1.2/src/lib.rs:44:19
  46: objc_exception::try
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_exception-0.1.2/src/lib.rs:67:9
  47: objc::exception::try
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/exception.rs:8:5
  48: objc::message::platform::send_unverified
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:26:5
  49: objc::message::send_message
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178:5
  50: druid_shell::backend::mac::window::key_down
             at /Users/davidroundy/misc-src/druid/druid-shell/src/backend/mac/window.rs:811:29
  51: <unknown>
  52: <unknown>
  53: <unknown>
  54: <unknown>
  55: <unknown>
  56: <() as objc::message::MessageArguments>::invoke
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  57: objc::message::platform::send_unverified::{{closure}}
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27:9
  58: objc_exception::try::{{closure}}
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_exception-0.1.2/src/lib.rs:68:31
  59: objc_exception::try_no_ret::try_objc_execute_closure
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_exception-0.1.2/src/lib.rs:34:9
  60: RustObjCExceptionTryCatch
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_exception-0.1.2/extern/exception.m:10:9
  61: objc_exception::try_no_ret
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_exception-0.1.2/src/lib.rs:44:19
  62: objc_exception::try
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc_exception-0.1.2/src/lib.rs:67:9
  63: objc::exception::try
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/exception.rs:8:5
  64: objc::message::platform::send_unverified
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:26:5
  65: objc::message::send_message
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178:5
  66: <*mut objc::runtime::Object as cocoa::appkit::NSApplication>::run
             at /Users/davidroundy/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.24.0/src/appkit.rs:438:9
  67: druid_shell::backend::mac::application::Application::run
             at /Users/davidroundy/misc-src/druid/druid-shell/src/backend/mac/application.rs:74:13
  68: druid_shell::application::Application::run
             at /Users/davidroundy/misc-src/druid/druid-shell/src/application.rs:150:9
  69: druid::app::AppLauncher<T>::launch
             at /Users/davidroundy/misc-src/druid/druid/src/app.rs:268:9
  70: breaks::main
             at ./src/main.rs:254:5
  71: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by cmyr** [comment]
Ah thanks, yea this must've been there forever; we were forwarding text input commands to our super view when we didn't have a text session, which was a mistake. Will have a fix shortly.
