### ISSUE TITLE
Main thread assertion failed 1 != 0

### ISSUE THREAD

**Issue by KiraResari** [linebender/druid#2243]
I was just trying to integrate Druid into my iced project to copy values to the clipboard.

However, on running my project afterwards, I got this panic:
```
thread 'main' panicked at 'Main thread assertion failed 1 != 0', C:\Users\Kira Recover\.cargo\registry\src\github.com-1ecc6299db9ec823\druid-shell-0.7.0\src\util.rs:39:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\std\src\panicking.rs:517
   1: std::panicking::begin_panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\std\src\panicking.rs:460
   2: druid_shell::util::assert_main_thread
             at C:\Users\Kira Recover\.cargo\registry\src\github.com-1ecc6299db9ec823\druid-shell-0.7.0\src\util.rs:39        
   3: druid_shell::application::Application::try_global
             at C:\Users\Kira Recover\.cargo\registry\src\github.com-1ecc6299db9ec823\druid-shell-0.7.0\src\application.rs:127
   4: druid_shell::application::Application::global
             at C:\Users\Kira Recover\.cargo\registry\src\github.com-1ecc6299db9ec823\druid-shell-0.7.0\src\application.rs:112
   5: kanji_tree::app::impl$1::new
             at .\src\app.rs:284
   6: iced::sandbox::impl$0::new<kanji_tree::app::KanjiTreeApp>
             at C:\Users\Kira Recover\.cargo\registry\src\github.com-1ecc6299db9ec823\iced-0.3.0\src\sandbox.rs:158
   7: iced::application::impl$1::new<kanji_tree::app::KanjiTreeApp>
             at C:\Users\Kira Recover\.cargo\registry\src\github.com-1ecc6299db9ec823\iced-0.3.0\src\application.rs:267
   8: iced_winit::application::run::closure$0<iced::application::Instance<kanji_tree::app::KanjiTreeApp>,iced_futures::executor::null::Null,iced_wgpu::window::compositor::Compositor>
             at C:\Users\Kira Recover\.cargo\registry\src\github.com-1ecc6299db9ec823\iced_winit-0.3.0\src\application.rs:135
   9: iced_futures::executor::Executor::enter<iced_futures::executor::null::Null,tuple$<iced::application::Instance<kanji_tree::app::KanjiTreeApp>,iced_futures::command::Command<enum$<kanji_tree::message::Message> > >,iced_winit::application::run::closure$0>
             at C:\Users\Kira Recover\.cargo\registry\src\github.com-1ecc6299db9ec823\iced_futures-0.3.0\src\executor.rs:66
  10: iced_futures::runtime::Runtime<iced_native::hasher::Hasher,tuple$<enum$<iced_native::event::Event>,enum$<iced_native::event::Status> >,iced_futures::executor::null::Null,iced_winit::proxy::Proxy<enum$<kanji_tree::message::Message> >,enum$<kanji_tree::mess
             at C:\Users\Kira Recover\.cargo\registry\src\github.com-1ecc6299db9ec823\iced_futures-0.3.0\src\runtime.rs:47
  11: iced_winit::application::run<iced::application::Instance<kanji_tree::app::KanjiTreeApp>,iced_futures::executor::null::Null,iced_wgpu::window::compositor::Compositor>
             at C:\Users\Kira Recover\.cargo\registry\src\github.com-1ecc6299db9ec823\iced_winit-0.3.0\src\application.rs:135
  12: iced::application::Application::run<kanji_tree::app::KanjiTreeApp>
             at C:\Users\Kira Recover\.cargo\registry\src\github.com-1ecc6299db9ec823\iced-0.3.0\src\application.rs:219
  13: kanji_tree::main
             at .\src\main.rs:12
  14: core::ops::function::FnOnce::call_once<enum$<core::result::Result<tuple$<>,enum$<iced::error::Error> >, 0, 2, Err> (*)(),tuple$<> >
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\core\src\ops\function.rs:227
```

I am hereby providing a branch of my project with the currently failing state:
https://github.com/KiraResari/kanji_tree/tree/druid_panics

This notably also happens if `let mut clipboard = Application::global().clipboard();` (as described in the sample here https://docs.rs/druid/latest/druid/struct.Clipboard.html ) is called directly before the copying as opposed to once at the start of the problem (as in the provided sample). In that case, the same error happens when the `copy_to_clipboard` function is called.

**Comment by xStrom** [comment]
You're trying to use just the clipboard without `Application::run` yeah? I think this issue was resolved in #1996.

Try using the latest Druid code by modifying your `Cargo.toml` and see if that fixes it.
```
--- druid = "0.7.0"
+++ druid = { git = "https://github.com/linebender/druid.git" }
```
